#import "/lib/trino-docs.typ": *

#anchor("doc-develop-client-protocol")
= Trino client REST API

The REST API allows clients to submit SQL queries to Trino and receive the results. Clients include the CLI, the JDBC driver, and others provided by the community. The preferred method to interact with Trino is using these existing clients. This document provides details about the API for reference. It can also be used to implement your own client, if necessary.

Find more information about client drivers, client applications, and the client protocol configuration in the #link(label("doc-client"))[client documentation].

== HTTP methods

- A #raw("POST") to #raw("/v1/statement") runs the query string in the #raw("POST") body, and returns a JSON document containing the query results. If there are more results, the JSON document contains a #raw("nextUri") URL attribute.
- A #raw("GET") to the #raw("nextUri") attribute returns the next batch of query results.
- A #raw("DELETE") to #raw("nextUri") terminates a running query.

== Overview of query processing

A Trino client request is initiated by an HTTP #raw("POST") to the endpoint #raw("/v1/statement"), with a #raw("POST") body consisting of the SQL query string. The caller may set various #link(label("ref-client-request-headers"))[Trino client REST API]. The headers are only required in the initial #raw("POST") request, and not when following the #raw("nextUri") links.

If the client request returns an HTTP 502, 503, or 504, that means there was an intermittent problem processing request and the client should try again in 50-100 ms. Trino does not generate those codes by itself, but those can be generated by load balancers in front of Trino.

Additionally, if the request returns a 429 status code, the client should retry the request using the #raw("Retry-After") header value provided.

Any HTTP status other than 502, 503, 504 or 200 means that query processing has failed.

The #raw("/v1/statement") #raw("POST") request returns a JSON document of type #raw("QueryResults"), as well as a collection of response headers. The #raw("QueryResults") document contains an #raw("error") field of type #raw("QueryError") if the query has failed, and if that object is not present, the query succeeded. Important aspects of #raw("QueryResults") are documented in the following sections.

If the #raw("data") field of the JSON document is set, it contains a list of the rows of data. The #raw("columns") field is set to a list of the names and types of the columns returned by the query. Most of the response headers are treated like browser cookies by the client, and echoed back as request headers in subsequent client requests, as documented below.

If the JSON document returned by the #raw("POST") to #raw("/v1/statement") does not contain a #raw("nextUri") link, the query has completed, either successfully or unsuccessfully, and no additional requests need to be made. If the #raw("nextUri") link is present in the document, there are more query results to be fetched. The client should loop executing a #raw("GET") request to the #raw("nextUri") returned in the #raw("QueryResults") response object until #raw("nextUri") is absent from the response.

The #raw("status") field of the JSON document is for human consumption only, and provides a hint about the query state. It cannot be used to tell if the query is finished.

== Important #raw("QueryResults") attributes

The most important attributes of the #raw("QueryResults") JSON document returned by the REST API endpoints are listed in this table. For more details, refer to the class #raw("io.trino.client.QueryResults") in module #raw("trino-client") in the #raw("client") directory of the Trino source code.

#list-table((
  ([Attribute], [Description],),
  ([#raw("id")], [The ID of the query.],),
  ([#raw("nextUri")], [If present, the URL to use for subsequent #raw("GET") or #raw("DELETE") requests. If not present, the query is complete or ended in error.],),
  ([#raw("columns")], [A list of the names and types of the columns returned by the query.],),
  ([#raw("data")], [The #raw("data") attribute contains a list of the rows returned by the query request. Each row is itself a list that holds values of the columns in the row, in the order specified by the #raw("columns") attribute.],),
  ([#raw("updateType")], [A human-readable string representing the operation. For a #raw("CREATE TABLE") request, the #raw("updateType") is "CREATE TABLE"; for #raw("SET SESSION") it is "SET SESSION"; etc.],),
  ([#raw("error")], [If query failed, the #raw("error") attribute contains a #raw("QueryError") object. That object contains a #raw("message"), an #raw("errorCode") and other information about the error. See the #raw("io.trino.client.QueryError") class in module #raw("trino-client") in the #raw("client") directory for more details.],)
), header-rows: 1, title: "QueryResults attributes")

== #raw("QueryResults") diagnostic attributes

These #raw("QueryResults") data members may be useful in tracking down problems:

#list-table((
  ([Attribute], [Type], [Description],),
  ([#raw("queryError")], [#raw("QueryError")], [Non-null only if the query resulted in an error.],),
  ([#raw("failureInfo")], [#raw("FailureInfo")], [#raw("failureInfo") has detail on the reason for the failure, including a stack trace, and #raw("FailureInfo.errorLocation"), providing the query line number and column number where the failure was detected.],),
  ([#raw("warnings")], [#raw("List<TrinoWarning>")], [A usually empty list of warnings.],),
  ([#raw("statementStats")], [#raw("StatementStats")], [A class containing statistics about the query execution. Of particular interest is #raw("StatementStats.rootStage"), of type #raw("StageStats"), providing statistics on the execution of each of the stages of query processing.],)
), header-rows: 1, title: "QueryResults diagnostic attributes")

#anchor("ref-client-request-headers")

== Client request headers

This table lists all supported client request headers. Many of the headers can be updated in the client as response headers, and supplied in subsequent requests, just like browser cookies.

#list-table((
  ([Header name], [Description],),
  ([#raw("X-Trino-User")], [Specifies the session user. If not supplied, the session user is automatically determined via #link(label("doc-security-user-mapping"))[User mapping].],),
  ([#raw("X-Trino-Original-User")], [Specifies the session's original user.],),
  ([#raw("X-Trino-Source")], [For reporting purposes, this supplies the name of the software that submitted the query.],),
  ([#raw("X-Trino-Catalog")], [The catalog context for query processing. Set by response header #raw("X-Trino-Set-Catalog").],),
  ([#raw("X-Trino-Schema")], [The schema context for query processing. Set by response header #raw("X-Trino-Set-Schema").],),
  ([#raw("X-Trino-Time-Zone")], [The timezone for query processing. Defaults to the timezone of the Trino cluster, and not the timezone of the client.],),
  ([#raw("X-Trino-Language")], [The language to use when processing the query and formatting results, formatted as a Java #raw("Locale") string, for example #raw("en-US") for US English. The language of the session can be set on a per-query basis using the #raw("X-Trino-Language") HTTP header.],),
  ([#raw("X-Trino-Trace-Token")], [Supplies a trace token to the Trino engine to help identify log lines that originate with this query request.],),
  ([#raw("X-Trino-Session")], [Supplies a comma-separated list of name=value pairs as session properties. When the Trino client run a #raw("SET SESSION name=value") query, the name=value pair is returned in the #raw("X-Set-Trino-Session") response header, and added to the client's list of session properties. If the response header #raw("X-Trino-Clear-Session") is returned, its value is the name of a session property that is removed from the client's accumulated list.],),
  ([#raw("X-Trino-Role")], [Sets the "role" for query processing. A "role" represents a collection of permissions. Set by response header #raw("X-Trino-Set-Role"). See #link(label("doc-sql-create-role"))[CREATE ROLE] to understand roles.],),
  ([#raw("X-Trino-Prepared-Statement")], [A comma-separated list of the name=value pairs, where the names are names of previously prepared SQL statements, and the values are keys that identify the executable form of the named prepared statements.],),
  ([#raw("X-Trino-Transaction-Id")], [The transaction ID to use for query processing. Set by response header #raw("X-Trino-Started-Transaction-Id") and cleared by #raw("X-Trino-Clear-Transaction-Id").],),
  ([#raw("X-Trino-Client-Info")], [Contains arbitrary information about the client program submitting the query.],),
  ([#raw("X-Trino-Client-Tags")], [A comma-separated list of "tag" strings, used to identify Trino resource groups.],),
  ([#raw("X-Trino-Client-Capabilities")], [A comma-separated list of optional protocol features supported by the client. Supported values include #raw("PATH"), #raw("PARAMETRIC_DATETIME"), #raw("NUMBER"), #raw("VARIANT"), #raw("VARIANT_BINARY"), and #raw("SESSION_AUTHORIZATION").],),
  ([#raw("X-Trino-Resource-Estimate")], [A comma-separated list of #raw("resource=value") type assignments. The possible choices of #raw("resource") are #raw("EXECUTION_TIME"), #raw("CPU_TIME"),  #raw("PEAK_MEMORY") and #raw("PEAK_TASK_MEMORY"). #raw("EXECUTION_TIME") and #raw("CPU_TIME") have values specified as airlift #raw("Duration") strings The format is a double precision number followed by a #raw("TimeUnit") string, for example #raw("s") for seconds, #raw("m") for minutes, #raw("h") for hours, etc. "PEAK\_MEMORY" and "PEAK\_TASK\_MEMORY" are specified as airlift #raw("DataSize") strings, whose format is an integer followed by #raw("B") for bytes; #raw("kB") for kilobytes; #raw("mB") for megabytes, #raw("gB") for gigabytes, etc.],),
  ([#raw("X-Trino-Extra-Credential")], [Provides extra credentials to the connector. The header is a name=value string that is saved in the session #raw("Identity") object. The name and value are only meaningful to the connector.],)
), header-rows: 1, title: "Client request headers")

== Client response headers

This table lists the supported client response headers. After receiving a response, a client must update the request headers used in subsequent requests to be consistent with the response headers received.

#list-table((
  ([Header name], [Description],),
  ([#raw("X-Trino-Set-Catalog")], [Instructs the client to set the catalog in the #raw("X-Trino-Catalog") request header in subsequent client requests.],),
  ([#raw("X-Trino-Set-Schema")], [Instructs the client to set the schema in the #raw("X-Trino-Schema") request header in subsequent client requests.],),
  ([#raw("X-Trino-Set-Authorization-User")], [Instructs the client to set the session authorization user in the #raw("X-Trino-User") request header in subsequent client requests. #raw("X-Trino-Original-User") should also be set.],),
  ([#raw("X-Trino-Reset-Authorization-User")], [Instructs the client to reset #raw("X-Trino-User") request header to its original value in subsequent client requests and remove #raw("X-Trino-Original-User") to reset the authorization user back to the original user.],),
  ([#raw("X-Trino-Set-Original-Roles")], [Instructs the client to set the roles of the original user in the #raw("X-Trino-Original-Roles") request header in subsequent client requests.],),
  ([#raw("X-Trino-Set-Session")], [The value of the #raw("X-Trino-Set-Session") response header is a string of the form #emph[property] = #emph[value]. It instructs the client include session property #emph[property] with value #emph[value] in the #raw("X-Trino-Session") header of subsequent client requests.],),
  ([#raw("X-Trino-Clear-Session")], [Instructs the client to remove the session property whose name is the value of the #raw("X-Trino-Clear-Session") header from the list of session properties in the #raw("X-Trino-Session") header in subsequent client requests.],),
  ([#raw("X-Trino-Set-Role")], [Instructs the client to set #raw("X-Trino-Role") request header to the catalog role supplied by the #raw("X-Trino-Set-Role") header in subsequent client requests.],),
  ([#raw("X-Trino-Added-Prepare")], [Instructs the client to add the name=value pair to the set of prepared statements in the #raw("X-Trino-Prepared-Statement") request header in subsequent client requests.],),
  ([#raw("X-Trino-Deallocated-Prepare")], [Instructs the client to remove the prepared statement whose name is the value of the #raw("X-Trino-Deallocated-Prepare") header from the client's list of prepared statements sent in the #raw("X-Trino-Prepared-Statement") request header in subsequent client requests.],),
  ([#raw("X-Trino-Started-Transaction-Id")], [Provides the transaction ID that the client should pass back in the #raw("X-Trino-Transaction-Id") request header in subsequent requests.],),
  ([#raw("X-Trino-Clear-Transaction-Id")], [Instructs the client to clear the #raw("X-Trino-Transaction-Id") request header in subsequent requests.],)
), header-rows: 1, title: "Client response headers")

== #raw("ProtocolHeaders")

Class #raw("io.trino.client.ProtocolHeaders") in module #raw("trino-client") in the #raw("client") directory of Trino source enumerates all the HTTP request and response headers allowed by the Trino client REST API.
