#import "/lib/trino-docs.typ": *

#anchor("doc-connector-prometheus")
= Prometheus connector

The Prometheus connector allows reading #link("https://prometheus.io/")[Prometheus] metrics as tables in Trino.

The mechanism for querying Prometheus is to use the Prometheus HTTP API. Specifically, all queries are resolved to Prometheus Instant queries with a form like: #link("http://localhost:9090/api/v1/query?query=up%5B21d%5D&time=1568229904.000")[http:\/\/localhost:9090\/api\/v1\/query?query=up\[21d\]&time=1568229904.000]. In this case the #raw("up") metric is taken from the Trino query table name, #raw("21d") is the duration of the query. The Prometheus #raw("time") value corresponds to the #raw("TIMESTAMP") field. Trino queries are translated from their use of the #raw("TIMESTAMP") field to a duration and time value as needed. Trino splits are generated by dividing the query range into attempted equal chunks.

== Requirements

To query Prometheus, you need:

- Network access from the Trino coordinator and workers to the Prometheus server. The default port is 9090.
- Prometheus version 2.15.1 or later.

== Configuration

Create #raw("etc/catalog/example.properties") to mount the Prometheus connector as the #raw("example") catalog, replacing the properties as appropriate:

#code-block("text", "connector.name=prometheus
prometheus.uri=http://localhost:9090
prometheus.query.chunk.size.duration=1d
prometheus.max.query.range.duration=21d
prometheus.cache.ttl=30s
prometheus.bearer.token.file=/path/to/bearer/token/file
prometheus.read-timeout=10s")

== Configuration properties

The following configuration properties are available:

#list-table((
  ([Property name], [Description], [Default],),
  ([#raw("prometheus.uri")], [Where to find Prometheus coordinator host.], [#raw("http://localhost:9090")],),
  ([#raw("prometheus.query.chunk.size.duration")], [The duration of each query to Prometheus. The equivalent catalog session property is #raw("query_chunk_size_duration").], [#raw("1d")],),
  ([#raw("prometheus.max.query.range.duration")], [Width of overall query to Prometheus, will be divided into #raw("prometheus.query.chunk.size.duration") queries. The equivalent catalog session property is #raw("max_query_range_duration").], [#raw("21d")],),
  ([#raw("prometheus.cache.ttl")], [How long values from this config file are cached.], [#raw("30s")],),
  ([#raw("prometheus.read-timeout")], [How much time a query to Prometheus has before timing out.], [#raw("10s")],),
  ([#raw("prometheus.auth.user")], [Username for basic authentication.], [],),
  ([#raw("prometheus.auth.password")], [Password for basic authentication.], [],),
  ([#raw("prometheus.auth.http.header.name")], [Name of the header to use for authorization.], [#raw("Authorization")],),
  ([#raw("prometheus.bearer.token.file")], [File holding bearer token if needed for access to Prometheus.], [],),
  ([#raw("prometheus.read-timeout")], [How much time a query to Prometheus has before timing out.], [#raw("10s")],),
  ([#raw("prometheus.case-insensitive-name-matching")], [Match Prometheus metric names case insensitively.], [#raw("false")],),
  ([#raw("prometheus.http.additional-headers")], [Additional headers to send to Prometheus endpoint. These headers must be comma-separated and delimited using #raw(":"). For example, #raw("header1:value1,header2:value2") sends two headers #raw("header1") and #raw("header2") with the values as #raw("value1") and #raw("value2"). Escape comma \(#raw(",")\) or colon\(#raw(":")\) characters in a header name or value with a backslash \(#raw("\\")\).], [],)
), header-rows: 1, title: "Prometheus configuration properties")

== Not exhausting your Trino available heap

The #raw("prometheus.query.chunk.size.duration") and #raw("prometheus.max.query.range.duration") are values to protect Trino from too much data coming back from Prometheus. The #raw("prometheus.max.query.range.duration") is the item of particular interest.

On a Prometheus instance that has been running for a while and depending on data retention settings, #raw("21d") might be far too much. Perhaps #raw("1h") might be a more reasonable setting. In the case of #raw("1h") it might be then useful to set #raw("prometheus.query.chunk.size.duration") to #raw("10m"), dividing the query window into 6 queries each of which can be handled in a Trino split.

Primarily query issuers can limit the amount of data returned by Prometheus by taking advantage of #raw("WHERE") clause limits on #raw("TIMESTAMP"), setting an upper bound and lower bound that define a relatively small window. For example:

#code-block("sql", "SELECT * FROM example.default.up WHERE TIMESTAMP > (NOW() - INTERVAL '10' second);")

If the query does not include a WHERE clause limit, these config settings are meant to protect against an unlimited query.

== Bearer token authentication

Prometheus can be setup to require a Authorization header with every query. The value in #raw("prometheus.bearer.token.file") allows for a bearer token to be read from the configured file. This file is optional and not required unless your Prometheus setup requires it. \
#raw("prometheus.auth.http.header.name") allows you to use a custom header name for bearer token. Default value is #raw("Authorization").

#anchor("ref-prometheus-type-mapping")

== Type mapping

Because Trino and Prometheus each support types that the other does not, this connector #link(label("ref-type-mapping-overview"))[modifies some types] when reading data.

The connector returns fixed columns that have a defined mapping to Trino types according to the following table:

#list-table((
  ([Prometheus column], [Trino type],),
  ([#raw("labels ")], [#raw("MAP(VARCHAR,VARCHAR) ")],),
  ([#raw("TIMESTAMP ")], [#raw("TIMESTAMP(3) WITH TIMEZONE ")],),
  ([#raw("value ")], [#raw("DOUBLE ")],)
), header-rows: 1, title: "Prometheus column to Trino type mapping")

No other types are supported.

The following example query result shows how the Prometheus #raw("up") metric is represented in Trino:

#code-block("sql", "SELECT * FROM example.default.up;")

#code-block("text", "                        labels                         |           timestamp            | value
--------------------------------------------------------+--------------------------------+-------
{instance=localhost:9090, job=prometheus, __name__=up} | 2022-09-01 06:18:54.481 +09:00 |   1.0
{instance=localhost:9090, job=prometheus, __name__=up} | 2022-09-01 06:19:09.446 +09:00 |   1.0
(2 rows)")

#anchor("ref-prometheus-sql-support")

== SQL support

The connector provides #link(label("ref-sql-globally-available"))[globally available] and #link(label("ref-sql-read-operations"))[read operation] statements to access data and metadata in Prometheus.
