#import "/lib/trino-docs.typ": *

#anchor("doc-release-release-454")
= Release 454 \(15 Aug 2024\)

== General

- Add support for retrieving lightweight query information from the #raw("/v1/query") endpoint with the #raw("pruned") query parameter. \(#issue("20843", "https://github.com/trinodb/trino/issues/20843")\)
- Add support for providing configuration for a secrets provider in a #raw("secrets.toml") file in the main Trino configuration directory. \(#issue("22633", "https://github.com/trinodb/trino/issues/22633")\)
- Add support for an event listener plugin that publishes events to Kafka. \(#issue("22426", "https://github.com/trinodb/trino/issues/22426")\)
- Add temporary support for restoring unsafe pushdown behavior removed in version 445. This can be enabled with the #raw("optimizer.allow-unsafe-pushdown") configuration property. When this mode is enabled, certain queries containing expressions that may fail for some inputs may fail at runtime. \(#issue("22987", "https://github.com/trinodb/trino/issues/22987")\)
- Improve performance of queries with multiple aggregations involving #raw("DISTINCT"). \(#issue("22355", "https://github.com/trinodb/trino/issues/22355")\)
- #breaking-marker("../release.html#breaking-changes") Improve query concurrency when memory is low by removing the #raw("query.low-memory-killer.delay") configuration property. \(#issue("22936", "https://github.com/trinodb/trino/issues/22936")\)
- Avoid retrying failed filesystem operations when they will always fail. \(#issue("22678", "https://github.com/trinodb/trino/issues/22678")\)
- Fix failure for queries involving #link(label("fn-json-parse"), raw("json_parse")) and a cast to #raw("array"), #raw("map"), or #raw("row"). \(#issue("22840", "https://github.com/trinodb/trino/issues/22840")\)
- Fix query failure when file-based network topology is configured with the #raw("node-scheduler.network-topology.file") configuration property. \(#issue("18793", "https://github.com/trinodb/trino/issues/18793")\)

== Web UI

- Add information about which tables and UDFs have been referenced by a query. \(#issue("20843", "https://github.com/trinodb/trino/issues/20843")\)

== JDBC driver

- Add support for the #raw("NO_GENERATED_KEYS") option in the #raw("Connection.prepareStatement") method. \(#issue("22100", "https://github.com/trinodb/trino/issues/22100")\)
- Fix the Trino username incorrectly defaulting to the name of the user running the Trino process when no username is specified. \(#issue("22901", "https://github.com/trinodb/trino/issues/22901")\)

== BigQuery connector

- Add support for the #raw("execute") procedure. \(#issue("22692", "https://github.com/trinodb/trino/issues/22692")\)

== Delta Lake connector

- Add S3 security mapping for the native S3 filesystem. \(#issue("22559", "https://github.com/trinodb/trino/issues/22559")\)
- Add support for writing #link("https://docs.delta.io/latest/delta-deletion-vectors.html")[deletion vectors]. \(#issue("17063", "https://github.com/trinodb/trino/issues/17063")\)
- Improve performance by caching table metadata to the metastore. \(#issue("21463", "https://github.com/trinodb/trino/issues/21463")\)
- #breaking-marker("../release.html#breaking-changes") Rename metastore OpenTelemetry attributes from #raw("trino.hive.*") to #raw("trino.metastore.*"). \(#issue("22866", "https://github.com/trinodb/trino/issues/22866")\)

== Hive connector

- Add support for using the #raw("hive.metastore-refresh-interval") configuration property when using Glue v2 Hive metastore. \(#issue("22706", "https://github.com/trinodb/trino/issues/22706")\)
- Add S3 security mapping for the native S3 filesystem. \(#issue("22559", "https://github.com/trinodb/trino/issues/22559")\)
- #breaking-marker("../release.html#breaking-changes") Rename metastore OpenTelemetry attributes from #raw("trino.hive.*") to #raw("trino.metastore.*"). \(#issue("22866", "https://github.com/trinodb/trino/issues/22866")\)
- Add support for adjusting UTC-adjusted #raw("INT64") timestamps to the timezone specified in the #raw("hive.parquet.time-zone") property when reading Parquet files. \(#issue("22577", "https://github.com/trinodb/trino/issues/22577")\)
- Fix potential query failure caused by incorrect bucket column validation. \(#issue("22261", "https://github.com/trinodb/trino/issues/22261")\)
- Fix error when reading #raw("INT96") timestamps in Parquet files generated by AWS Wrangler. \(#issue("22854", "https://github.com/trinodb/trino/issues/22854")\)

== Hudi connector

- Add S3 security mapping for the native S3 filesystem. \(#issue("22559", "https://github.com/trinodb/trino/issues/22559")\)
- #breaking-marker("../release.html#breaking-changes") Rename metastore OpenTelemetry attributes from #raw("trino.hive.*") to #raw("trino.metastore.*"). \(#issue("22866", "https://github.com/trinodb/trino/issues/22866")\)

== Iceberg connector

- Add S3 security mapping for the native S3 filesystem. \(#issue("22559", "https://github.com/trinodb/trino/issues/22559")\)
- Add support for changing a column's type from #raw("tinyint") or #raw("smallint") to #raw("integer"). \(#issue("19971", "https://github.com/trinodb/trino/issues/19971")\)
- Improve query planning performance by caching Iceberg metadata files on the coordinator. This behavior can be disabled by setting the new #raw("iceberg.metadata-cache.enabled") configuration property to #raw("false"). \(#issue("22739", "https://github.com/trinodb/trino/issues/22739")\)
- #breaking-marker("../release.html#breaking-changes") Rename metastore OpenTelemetry attributes from #raw("trino.hive.*") to #raw("trino.metastore.*"). \(#issue("22866", "https://github.com/trinodb/trino/issues/22866")\)

== Memory connector

- Fix incorrect results after truncating tables. \(#issue("22665", "https://github.com/trinodb/trino/issues/22665")\)

== Oracle connector

- Add support for specifying the JDBC fetch size with the #raw("oracle.fetch-size") configuration property. \(#issue("22670", "https://github.com/trinodb/trino/issues/22670")\)

== PostgreSQL connector

- Add support for specifying the JDBC fetch size with the #raw("postgresql.fetch-size") configuration property. \(#issue("22670", "https://github.com/trinodb/trino/issues/22670")\)
- Improve performance when using the #raw("euclidean_distance") and #raw("cosine_distance") functions on #raw("vector") types. \(#issue("22618", "https://github.com/trinodb/trino/issues/22618")\)
- Improve performance when a query contains #raw("-dot_product") projections. \(#issue("23015", "https://github.com/trinodb/trino/issues/23015")\)
- Fix failure when a user-defined type name contains uppercase characters. \(#issue("22848", "https://github.com/trinodb/trino/issues/22848")\)

== Redshift connector

- Add support for specifying the JDBC fetch size with the #raw("redshift.fetch-size") configuration property. \(#issue("22670", "https://github.com/trinodb/trino/issues/22670")\)
