#import "/lib/trino-docs.typ": *

#anchor("doc-release-release-410")
= Release 410 \(8 Mar 2023\)

== General

- Improve performance of certain queries with unions. \(#issue("16019", "https://github.com/trinodb/trino/issues/16019")\)
- Fix potential query failure when using an #raw("ORDER BY") clause while spilling to disk is enabled. \(#issue("16406", "https://github.com/trinodb/trino/issues/16406")\)
- Fix potential query failure when performing a #raw("JOIN") with a comparison between two different types. \(#issue("16444", "https://github.com/trinodb/trino/issues/16444")\)

== Delta Lake connector

- Fix query failure when reading Parquet files generated by Airbyte. \(#issue("16362", "https://github.com/trinodb/trino/issues/16362")\)

== Google Sheets connector

- Add support for the #link(label("ref-google-sheets-sheet-function"))[#raw("sheet") table function]. \(#issue("12502", "https://github.com/trinodb/trino/issues/12502")\)

== Hive connector

- Add support for AWS Security Token Support with S3 Select. \(#issue("5947", "https://github.com/trinodb/trino/issues/5947")\)
- Fix incorrectly ignoring the #raw("hive.timestamp-precision") configuration property in Hive views. \(#issue("6295", "https://github.com/trinodb/trino/issues/6295")\)
- Fix query failure when reading Parquet files generated by Airbyte. \(#issue("16362", "https://github.com/trinodb/trino/issues/16362")\)
- Fix incorrect results when using a value with uppercase characters for the #raw("partition_projection_location_template") table property. \(#issue("16349", "https://github.com/trinodb/trino/issues/16349")\)

== Hudi connector

- Fix query failure when reading Parquet files generated by Airbyte. \(#issue("16362", "https://github.com/trinodb/trino/issues/16362")\)

== Iceberg connector

- Improve file pruning when generating Iceberg table statistics. \(#issue("16244", "https://github.com/trinodb/trino/issues/16244")\)
- Fix query failure when reading Parquet files generated by Airbyte. \(#issue("16362", "https://github.com/trinodb/trino/issues/16362")\)

== Ignite connector

- Add support for #link(label("ref-aggregation-pushdown"))[aggregation pushdown] of the #raw("count(distinct)") function. \(#issue("16342", "https://github.com/trinodb/trino/issues/16342")\)
