#import "/lib/trino-docs.typ": *

#anchor("doc-sql")
= SQL statement syntax

This section describes the syntax for SQL statements that can be executed in Trino.

Refer to the following sections for further details:

- #link(label("doc-language"))[SQL data types and other general aspects]
- #link(label("doc-functions"))[SQL functions and operators]

- #link(label("doc-sql-alter-branch"))[ALTER BRANCH]
- #link(label("doc-sql-alter-materialized-view"))[ALTER MATERIALIZED VIEW]
- #link(label("doc-sql-alter-schema"))[ALTER SCHEMA]
- #link(label("doc-sql-alter-table"))[ALTER TABLE]
- #link(label("doc-sql-alter-view"))[ALTER VIEW]
- #link(label("doc-sql-analyze"))[ANALYZE]
- #link(label("doc-sql-call"))[CALL]
- #link(label("doc-sql-comment"))[COMMENT]
- #link(label("doc-sql-commit"))[COMMIT]
- #link(label("doc-sql-create-branch"))[CREATE BRANCH]
- #link(label("doc-sql-create-catalog"))[CREATE CATALOG]
- #link(label("doc-sql-create-function"))[CREATE FUNCTION]
- #link(label("doc-sql-create-materialized-view"))[CREATE MATERIALIZED VIEW]
- #link(label("doc-sql-create-role"))[CREATE ROLE]
- #link(label("doc-sql-create-schema"))[CREATE SCHEMA]
- #link(label("doc-sql-create-table"))[CREATE TABLE]
- #link(label("doc-sql-create-table-as"))[CREATE TABLE AS]
- #link(label("doc-sql-create-view"))[CREATE VIEW]
- #link(label("doc-sql-deallocate-prepare"))[DEALLOCATE PREPARE]
- #link(label("doc-sql-delete"))[DELETE]
- #link(label("doc-sql-deny"))[DENY]
- #link(label("doc-sql-describe"))[DESCRIBE]
- #link(label("doc-sql-describe-input"))[DESCRIBE INPUT]
- #link(label("doc-sql-describe-output"))[DESCRIBE OUTPUT]
- #link(label("doc-sql-drop-branch"))[DROP BRANCH]
- #link(label("doc-sql-drop-catalog"))[DROP CATALOG]
- #link(label("doc-sql-drop-function"))[DROP FUNCTION]
- #link(label("doc-sql-drop-materialized-view"))[DROP MATERIALIZED VIEW]
- #link(label("doc-sql-drop-role"))[DROP ROLE]
- #link(label("doc-sql-drop-schema"))[DROP SCHEMA]
- #link(label("doc-sql-drop-table"))[DROP TABLE]
- #link(label("doc-sql-drop-view"))[DROP VIEW]
- #link(label("doc-sql-execute"))[EXECUTE]
- #link(label("doc-sql-execute-immediate"))[EXECUTE IMMEDIATE]
- #link(label("doc-sql-explain"))[EXPLAIN]
- #link(label("doc-sql-explain-analyze"))[EXPLAIN ANALYZE]
- #link(label("doc-sql-grant"))[GRANT privilege]
- #link(label("doc-sql-grant-roles"))[GRANT role]
- #link(label("doc-sql-insert"))[INSERT]
- #link(label("doc-sql-match-recognize"))[MATCH\_RECOGNIZE]
- #link(label("doc-sql-merge"))[MERGE]
- #link(label("doc-sql-prepare"))[PREPARE]
- #link(label("doc-sql-refresh-materialized-view"))[REFRESH MATERIALIZED VIEW]
- #link(label("doc-sql-reset-session"))[RESET SESSION]
- #link(label("doc-sql-reset-session-authorization"))[RESET SESSION AUTHORIZATION]
- #link(label("doc-sql-revoke"))[REVOKE privilege]
- #link(label("doc-sql-revoke-roles"))[REVOKE role]
- #link(label("doc-sql-rollback"))[ROLLBACK]
- #link(label("doc-sql-select"))[SELECT]
- #link(label("doc-sql-set-path"))[SET PATH]
- #link(label("doc-sql-set-role"))[SET ROLE]
- #link(label("doc-sql-set-session"))[SET SESSION]
- #link(label("doc-sql-set-session-authorization"))[SET SESSION AUTHORIZATION]
- #link(label("doc-sql-set-time-zone"))[SET TIME ZONE]
- #link(label("doc-sql-show-branches"))[SHOW BRANCHES]
- #link(label("doc-sql-show-catalogs"))[SHOW CATALOGS]
- #link(label("doc-sql-show-columns"))[SHOW COLUMNS]
- #link(label("doc-sql-show-create-function"))[SHOW CREATE FUNCTION]
- #link(label("doc-sql-show-create-materialized-view"))[SHOW CREATE MATERIALIZED VIEW]
- #link(label("doc-sql-show-create-schema"))[SHOW CREATE SCHEMA]
- #link(label("doc-sql-show-create-table"))[SHOW CREATE TABLE]
- #link(label("doc-sql-show-create-view"))[SHOW CREATE VIEW]
- #link(label("doc-sql-show-functions"))[SHOW FUNCTIONS]
- #link(label("doc-sql-show-grants"))[SHOW GRANTS]
- #link(label("doc-sql-show-role-grants"))[SHOW ROLE GRANTS]
- #link(label("doc-sql-show-roles"))[SHOW ROLES]
- #link(label("doc-sql-show-schemas"))[SHOW SCHEMAS]
- #link(label("doc-sql-show-session"))[SHOW SESSION]
- #link(label("doc-sql-show-stats"))[SHOW STATS]
- #link(label("doc-sql-show-tables"))[SHOW TABLES]
- #link(label("doc-sql-start-transaction"))[START TRANSACTION]
- #link(label("doc-sql-truncate"))[TRUNCATE]
- #link(label("doc-sql-update"))[UPDATE]
- #link(label("doc-sql-use"))[USE]
- #link(label("doc-sql-values"))[VALUES]

- #link(label("doc-sql-pattern-recognition-in-window"))[Row pattern recognition in window structures]
